import { useIndex } from "./lib/api";
import { useNavigate, useRoute } from "./lib/router";
import { Overview } from "./components/Overview";
import { RunView } from "./components/RunView";

export default function App() {
  const { data: index, isLoading, error } = useIndex();
  const route = useRoute();
  const navigate = useNavigate();

  const tiers = index?.tiers ?? [];
  const selectedKey = (route.tierKey && tiers.find((t) => t.key === route.tierKey)?.key) || tiers[0]?.key;
  const selectedTier = tiers.find((t) => t.key === selectedKey);
  const run = route.runId ? selectedTier?.runs.find((r) => r.id === route.runId) : undefined;

  return (
    <div className="min-h-full">
      <div className="mx-auto max-w-[1100px] px-6 pb-20 pt-10">
        <nav className="mb-7 flex flex-wrap items-center gap-x-3 gap-y-2">
          <button onClick={() => navigate()} className="text-xl font-semibold tracking-tight text-base-content">
            Last Light <span className="text-accent">·</span> <span className="text-base-content/70">Evals</span>
          </button>
          <div className="ml-auto flex flex-wrap gap-2">
            {tiers.map((t) => (
              <button
                key={t.key}
                onClick={() => navigate(t.key)}
                className={
                  "rounded-lg border px-3 py-1.5 font-mono text-xs font-semibold " +
                  (t.key === selectedKey
                    ? "border-info bg-info/15 text-info"
                    : "border-base-300 bg-base-200 text-base-content/60 hover:border-info hover:text-base-content")
                }
              >
                {t.key}
                <span className="ml-1.5 text-base-content/40">{t.runs.length}</span>
              </button>
            ))}
          </div>
        </nav>

        {error && (
          <div className="rounded-xl border border-error/40 bg-error/10 px-4 py-3 font-mono text-xs text-error">
            Couldn't load the index: {(error as Error).message}
          </div>
        )}

        {isLoading && !index ? (
          <div className="py-16 text-center font-mono text-sm text-base-content/40">loading…</div>
        ) : !tiers.length ? (
          <Empty />
        ) : run ? (
          <div>
            <button
              onClick={() => navigate(selectedKey)}
              className="mb-5 font-mono text-xs text-info hover:underline"
            >
              ← all {selectedKey} runs
            </button>
            <RunView run={run} />
          </div>
        ) : selectedTier ? (
          <div>
            <h1 className="mb-1 text-2xl font-semibold text-base-content">{selectedTier.key}</h1>
            <p className="mb-6 font-mono text-xs text-base-content/50">
              {selectedTier.runs.length} run{selectedTier.runs.length === 1 ? "" : "s"} · click a run to open its scorecard
            </p>
            <Overview tier={selectedTier} />
          </div>
        ) : null}

        <footer className="mt-12 border-t border-base-300 pt-5 font-mono text-2xs text-base-content/40">
          Real production workflows · mocked GitHub · deterministic grading. ★ = best in column. Generated by{" "}
          <span className="text-base-content/60">lastlight-evals run</span>.
        </footer>
      </div>
    </div>
  );
}

function Empty() {
  return (
    <div className="rounded-xl border border-base-300 bg-base-200 px-5 py-10 text-center">
      <p className="font-mono text-sm text-base-content/60">No runs yet.</p>
      <p className="mt-2 font-mono text-xs text-base-content/40">
        Run <span className="text-accent">lastlight-evals run</span> to record one.
      </p>
    </div>
  );
}
