import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { DEFAULT_ALLOWLIST } from "./egress-allowlist.js";

/**
 * Tinyproxy config generation for the docker sandbox backend.
 *
 * The harness writes two configs to `$STATE_DIR/proxy/` at boot:
 *   - `strict.conf` — destination allowlist drawn from `egress-allowlist.ts`.
 *   - `open.conf`   — no destination filter; only the private-IP floor.
 *
 * Both files are bind-mounted into the `tinyproxy-strict` and
 * `tinyproxy-open` services declared in `docker-compose.yml`. A sandbox
 * container's `HTTPS_PROXY` env var picks one based on the phase's
 * `unrestricted_egress` flag.
 *
 * Tinyproxy filters HTTPS traffic by inspecting the destination of the
 * client's `CONNECT` request — no TLS interception. That's sufficient for
 * the "stop exfil to attacker-controlled hosts" threat we care about.
 */

const PROXY_PORT = 8888;

/** RFC1918 + loopback + link-local — blocked unconditionally when the toggle is on. */
const PRIVATE_IP_DENY = [
  "10.0.0.0/8",
  "172.16.0.0/12",
  "192.168.0.0/16",
  "127.0.0.0/8",
  "169.254.0.0/16",
];

export interface TinyproxyConfigOptions {
  /**
   * When true, both configs emit `Deny` rules covering RFC1918, loopback,
   * and link-local CIDRs. Independent of the strict/open allowlist
   * distinction — sandbox traffic to private addresses is almost always
   * SSRF (docker metadata, harness internals) regardless of phase intent.
   *
   * Default: read from `LASTLIGHT_BLOCK_PRIVATE_IPS` env var; treats
   * anything other than `0`/`false`/`no` as enabled. Defaults to enabled
   * if the env var is unset.
   */
  blockPrivateIps?: boolean;
}

function privateIpBlockEnabled(): boolean {
  const raw = (process.env.LASTLIGHT_BLOCK_PRIVATE_IPS ?? "").toLowerCase().trim();
  if (raw === "" ) return true;
  return !(raw === "0" || raw === "false" || raw === "no");
}

/** Build the contents of the strict tinyproxy.conf. */
export function renderStrictConf(opts: TinyproxyConfigOptions = {}): string {
  const blockPrivate = opts.blockPrivateIps ?? privateIpBlockEnabled();
  return [
    "# Generated by lastlight at harness boot. DO NOT EDIT BY HAND —",
    "# the source of truth is src/sandbox/egress-allowlist.ts.",
    "",
    `Port ${PROXY_PORT}`,
    "Listen 0.0.0.0",
    "Timeout 600",
    "DefaultErrorFile \"/usr/share/tinyproxy/default.html\"",
    "StatHost \"tinyproxy.stats\"",
    "LogLevel Info",
    "MaxClients 100",
    "",
    "# Anyone on the docker network can use this proxy. The docker network",
    "# itself is `internal` (no host egress), so this is not an open relay.",
    "Allow 0.0.0.0/0",
    "",
    ...(blockPrivate ? renderPrivateIpDenies() : ["# Private-IP blocking disabled (LASTLIGHT_BLOCK_PRIVATE_IPS=0)."]),
    "",
    "# HTTPS CONNECT — restricted to 443 so the agent can't tunnel to",
    "# arbitrary services on allowlisted hosts.",
    "ConnectPort 443",
    "",
    "# Destination allowlist. Anything not matching one of these Filter",
    "# entries is rejected with a 403.",
    "FilterDefaultDeny Yes",
    "FilterCaseSensitive No",
    "FilterExtended Yes",
    "FilterURLs Off",
    `Filter "${proxyFilterPath()}"`,
    "",
  ].join("\n");
}

/** Build the contents of the open tinyproxy.conf. */
export function renderOpenConf(opts: TinyproxyConfigOptions = {}): string {
  const blockPrivate = opts.blockPrivateIps ?? privateIpBlockEnabled();
  return [
    "# Generated by lastlight at harness boot. DO NOT EDIT BY HAND.",
    "# This proxy intentionally has no destination allowlist — it's used",
    "# only by phases that declare `unrestricted_egress: true`.",
    "",
    `Port ${PROXY_PORT}`,
    "Listen 0.0.0.0",
    "Timeout 600",
    "DefaultErrorFile \"/usr/share/tinyproxy/default.html\"",
    "StatHost \"tinyproxy.stats\"",
    "LogLevel Info",
    "MaxClients 100",
    "",
    "Allow 0.0.0.0/0",
    "",
    ...(blockPrivate ? renderPrivateIpDenies() : ["# Private-IP blocking disabled (LASTLIGHT_BLOCK_PRIVATE_IPS=0)."]),
    "",
    "ConnectPort 443",
    "",
    "# No Filter directive — every destination is allowed (subject to the",
    "# private-IP denies above when LASTLIGHT_BLOCK_PRIVATE_IPS is enabled).",
    "",
  ].join("\n");
}

/** Build the contents of the destination-host filter file. */
export function renderFilterList(): string {
  // Tinyproxy's filter file matches one host per line. The expressions are
  // regex when FilterExtended is Yes; anchor each entry so a host like
  // `bad.api.github.com.example.com` can't sneak through via substring.
  const lines = [
    "# Generated by lastlight from src/sandbox/egress-allowlist.ts.",
    "# Edit the TypeScript source, not this file.",
    "",
  ];
  for (const host of DEFAULT_ALLOWLIST) {
    // Escape literal dots; allow the host on its own or as a subdomain
    // suffix (e.g. raw.githubusercontent.com still matches when the agent
    // hits a path under it).
    const escaped = host.replaceAll(".", "\\.");
    lines.push(`(^|\\.)${escaped}$`);
  }
  lines.push("");
  return lines.join("\n");
}

function renderPrivateIpDenies(): string[] {
  return [
    "# Block sandbox traffic to private address space to stop SSRF into",
    "# the docker network, host loopback, and cloud metadata services.",
    "# Toggle off via LASTLIGHT_BLOCK_PRIVATE_IPS=0.",
    ...PRIVATE_IP_DENY.map((cidr) => `Deny ${cidr}`),
  ];
}

function proxyFilterPath(): string {
  // Path inside the tinyproxy container — matches the agent-data volume
  // mount declared in docker-compose.yml. The harness writes filter.txt
  // alongside strict.conf at $STATE_DIR/proxy/, which the proxies see at
  // /app/data/proxy/ inside their containers.
  return "/app/data/proxy/filter.txt";
}

/**
 * Write strict.conf, open.conf, and filter.txt under $STATE_DIR/proxy/.
 * Idempotent — safe to call on every boot. Returns the directory path so
 * docker-compose / SIGHUP wiring can find the files.
 */
export function writeProxyConfigs(stateDir: string, opts: TinyproxyConfigOptions = {}): string {
  const proxyDir = join(stateDir, "proxy");
  mkdirSync(proxyDir, { recursive: true });
  writeFileSync(join(proxyDir, "strict.conf"), renderStrictConf(opts));
  writeFileSync(join(proxyDir, "open.conf"), renderOpenConf(opts));
  writeFileSync(join(proxyDir, "filter.txt"), renderFilterList());
  return proxyDir;
}

export const TINYPROXY_PORT = PROXY_PORT;
