#!/usr/bin/env node
/**
 * Last Light setup wizard — `npx lastlight setup`
 *
 * Guides a user from a bare server to a fully configured Last Light instance.
 * Uses only Node.js built-ins: readline/promises, crypto, fs, child_process.
 * Zero new dependencies.
 */

import { createInterface } from "node:readline/promises";
import { randomBytes } from "node:crypto";
import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  chmodSync,
  copyFileSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { execSync } from "node:child_process";

// ── Types ───────────────────────────────────────────────────────────────────

export interface SetupConfig {
  GITHUB_APP_ID: string;
  GITHUB_APP_INSTALLATION_ID: string;
  WEBHOOK_SECRET: string;
  ADMIN_SECRET: string;
  DOMAIN: string;
  ANTHROPIC_API_KEY: string;
  ADMIN_PASSWORD?: string;
  SLACK_BOT_TOKEN?: string;
  SLACK_APP_TOKEN?: string;
  SLACK_DELIVERY_CHANNEL?: string;
  SLACK_ALLOWED_USERS?: string;
  useCaddy: boolean;
  pemSourcePath: string;
}

// ── Validation helpers (exported for unit tests) ────────────────────────────

/** Returns true if the string is a positive integer (no decimals, no leading spaces). */
export function isPositiveInt(s: string): boolean {
  return /^\d+$/.test(s) && parseInt(s, 10) > 0;
}

/**
 * Returns true if the file at `filePath` exists and starts with a PEM header.
 * Accepts both RSA PRIVATE KEY and PKCS8 PRIVATE KEY formats.
 */
export function isPemFile(filePath: string): boolean {
  try {
    const content = readFileSync(filePath, "utf8");
    return (
      content.startsWith("-----BEGIN RSA PRIVATE KEY-----") ||
      content.startsWith("-----BEGIN PRIVATE KEY-----")
    );
  } catch {
    return false;
  }
}

/** Returns true if the key has the `sk-ant-` prefix. */
export function isAnthropicKey(s: string): boolean {
  return s.startsWith("sk-ant-");
}

/** Returns true if the token has the `xoxb-` prefix. */
export function isSlackBotToken(s: string): boolean {
  return s.startsWith("xoxb-");
}

/** Returns true if the token has the `xapp-` prefix. */
export function isSlackAppToken(s: string): boolean {
  return s.startsWith("xapp-");
}

// ── .env serialization (exported for unit tests) ────────────────────────────

/** Builds the full .env file content from the collected config. */
export function buildEnvContent(config: SetupConfig): string {
  const lines: string[] = [
    "# ── Last Light — Environment Variables ─────────────────────",
    "# Generated by: npx lastlight setup",
    "",
    "# ── GitHub App (required) ────────────────────────────────",
    `GITHUB_APP_ID=${config.GITHUB_APP_ID}`,
    `GITHUB_APP_PRIVATE_KEY_PATH=./secrets/app.pem`,
    `GITHUB_APP_INSTALLATION_ID=${config.GITHUB_APP_INSTALLATION_ID}`,
    "",
    "# ── Webhook (required) ──────────────────────────────────",
    `WEBHOOK_SECRET=${config.WEBHOOK_SECRET}`,
    "",
    "# ── Domain (used by Caddy for TLS) ─────────────────────────────────────",
    `DOMAIN=${config.DOMAIN}`,
    "",
    "# ── Claude API ───────────────────────────────────────────",
    `ANTHROPIC_API_KEY=${config.ANTHROPIC_API_KEY}`,
    "",
    "# ── Admin Dashboard ────────────────────────────────────────",
    `ADMIN_SECRET=${config.ADMIN_SECRET}`,
  ];

  if (config.ADMIN_PASSWORD) {
    lines.push(`ADMIN_PASSWORD=${config.ADMIN_PASSWORD}`);
  }

  if (config.SLACK_BOT_TOKEN) {
    lines.push("");
    lines.push("# ── Slack ──────────────────────────────────────────────────");
    lines.push(`SLACK_BOT_TOKEN=${config.SLACK_BOT_TOKEN}`);
    if (config.SLACK_APP_TOKEN) {
      lines.push(`SLACK_APP_TOKEN=${config.SLACK_APP_TOKEN}`);
    }
    if (config.SLACK_DELIVERY_CHANNEL) {
      lines.push(`SLACK_DELIVERY_CHANNEL=${config.SLACK_DELIVERY_CHANNEL}`);
    }
    if (config.SLACK_ALLOWED_USERS) {
      lines.push(`SLACK_ALLOWED_USERS=${config.SLACK_ALLOWED_USERS}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

// ── Interactive helpers ─────────────────────────────────────────────────────

type Validator = (value: string) => boolean;

async function prompt(
  rl: ReturnType<typeof createInterface>,
  question: string,
  validator?: Validator,
  errorMsg?: string
): Promise<string> {
  while (true) {
    const answer = (await rl.question(question)).trim();
    if (!validator || validator(answer)) return answer;
    console.error(`  ${errorMsg ?? "Invalid input. Please try again."}`);
  }
}

async function promptYesNo(
  rl: ReturnType<typeof createInterface>,
  question: string,
  defaultYes = false
): Promise<boolean> {
  const hint = defaultYes ? "[Y/n]" : "[y/N]";
  while (true) {
    const answer = (await rl.question(`${question} ${hint}: `)).trim().toLowerCase();
    if (answer === "" ) return defaultYes;
    if (answer === "y" || answer === "yes") return true;
    if (answer === "n" || answer === "no") return false;
    console.error("  Please enter y or n.");
  }
}

// ── Setup steps ─────────────────────────────────────────────────────────────

function preflight(): void {
  // Check for docker-compose.yml; clone if not present, then cd into it
  if (!existsSync("docker-compose.yml")) {
    // Maybe we're one level up and a `lastlight/` clone already exists
    if (existsSync("lastlight/docker-compose.yml")) {
      console.log("\nFound existing lastlight/ directory — continuing setup there.\n");
      process.chdir("lastlight");
    } else {
      console.log("\nNo docker-compose.yml found in current directory.");
      console.log("Cloning cliftonc/lastlight into ./lastlight ...\n");
      try {
        execSync("git clone https://github.com/cliftonc/lastlight.git lastlight", {
          stdio: "inherit",
        });
      } catch {
        console.error("Failed to clone repository. Please clone it manually:");
        console.error("  git clone https://github.com/cliftonc/lastlight.git");
        process.exit(1);
      }
      process.chdir("lastlight");
      console.log(`\nContinuing setup in ${process.cwd()}\n`);
    }
  }

  // Check Docker is available
  try {
    execSync("docker info", { stdio: "ignore" });
  } catch {
    console.error("\nDocker is not running or not installed.");
    console.error("Please start Docker and re-run: npx lastlight setup\n");
    process.exit(1);
  }

  // Check .env doesn't already exist
  if (existsSync(".env")) {
    console.error("\n.env already exists. To reconfigure, edit it directly.");
    console.error("If you want to start over, remove it first: rm .env\n");
    process.exit(1);
  }
}

async function collectGitHubApp(
  rl: ReturnType<typeof createInterface>
): Promise<{ appId: string; installationId: string; pemSourcePath: string }> {
  console.log("\n── Step 1: GitHub App ─────────────────────────────────────");
  console.log(
    "Create a GitHub App at https://github.com/settings/apps/new if you haven't already.\n"
  );

  const appId = await prompt(
    rl,
    "GitHub App ID (numeric): ",
    isPositiveInt,
    "Must be a positive integer (e.g. 123456)."
  );

  const installationId = await prompt(
    rl,
    "GitHub App Installation ID (numeric): ",
    isPositiveInt,
    "Must be a positive integer (e.g. 789012)."
  );

  const pemPath = await prompt(
    rl,
    "Path to GitHub App private key (.pem): ",
    (p) => isPemFile(resolve(p)),
    "File not found or does not look like a PEM private key."
  );

  return {
    appId,
    installationId,
    pemSourcePath: resolve(pemPath),
  };
}

function generateSecrets(): { webhookSecret: string; adminSecret: string } {
  console.log("\n── Step 2: Secrets ────────────────────────────────────────");
  const webhookSecret = randomBytes(32).toString("hex");
  const adminSecret = randomBytes(32).toString("hex");

  console.log("\nAuto-generated WEBHOOK_SECRET (paste this into your GitHub App webhook settings):");
  console.log(`  ${webhookSecret}\n`);

  return { webhookSecret, adminSecret };
}

async function collectDomain(
  rl: ReturnType<typeof createInterface>
): Promise<{ domain: string; useCaddy: boolean }> {
  console.log("── Step 3: Domain + TLS ───────────────────────────────────");

  const domain = await prompt(
    rl,
    "Your domain (e.g. lastlight.example.com): ",
    (d) => d.length > 0 && d.includes("."),
    "Please enter a valid domain name."
  );

  const useCaddy = await promptYesNo(
    rl,
    "Use Caddy for automatic TLS (recommended)?",
    true
  );

  console.log(`\nWebhook URL: https://${domain}/webhook`);

  return { domain, useCaddy };
}

async function collectAnthropicKey(
  rl: ReturnType<typeof createInterface>
): Promise<string> {
  console.log("\n── Step 4: Anthropic API Key ──────────────────────────────");
  return prompt(
    rl,
    "ANTHROPIC_API_KEY (sk-ant-...): ",
    isAnthropicKey,
    "Must start with sk-ant-"
  );
}

async function collectAdminPassword(
  rl: ReturnType<typeof createInterface>
): Promise<string | undefined> {
  console.log("\n── Step 5: Admin Dashboard Password ──────────────────────");
  const wantPassword = await promptYesNo(
    rl,
    "Set an admin dashboard password?",
    false
  );
  if (!wantPassword) return undefined;

  return prompt(
    rl,
    "Admin password: ",
    (p) => p.length >= 8,
    "Password must be at least 8 characters."
  );
}

async function collectSlack(rl: ReturnType<typeof createInterface>): Promise<{
  botToken?: string;
  appToken?: string;
  deliveryChannel?: string;
  allowedUsers?: string;
}> {
  console.log("\n── Step 6: Slack (optional) ───────────────────────────────");
  const wantSlack = await promptYesNo(rl, "Enable Slack integration?", false);
  if (!wantSlack) return {};

  const botToken = await prompt(
    rl,
    "SLACK_BOT_TOKEN (xoxb-...): ",
    isSlackBotToken,
    "Must start with xoxb-"
  );

  const appToken = await prompt(
    rl,
    "SLACK_APP_TOKEN (xapp-...): ",
    isSlackAppToken,
    "Must start with xapp-"
  );

  const deliveryChannelRaw = (
    await rl.question("SLACK_DELIVERY_CHANNEL (optional, press Enter to skip): ")
  ).trim();
  const deliveryChannel = deliveryChannelRaw || undefined;

  const allowedUsersRaw = (
    await rl.question(
      "SLACK_ALLOWED_USERS (optional comma-separated user IDs, press Enter to skip): "
    )
  ).trim();
  const allowedUsers = allowedUsersRaw || undefined;

  return { botToken, appToken, deliveryChannel, allowedUsers };
}

function writeConfig(config: SetupConfig): void {
  console.log("\n── Step 7: Writing config ─────────────────────────────────");

  // Create secrets/ directory
  try {
    mkdirSync("secrets", { recursive: true });
  } catch (err: unknown) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === "EACCES") {
      console.error("Permission denied creating secrets/ directory.");
      process.exit(1);
    }
    throw err;
  }

  // Copy PEM to secrets/app.pem
  copyFileSync(config.pemSourcePath, join("secrets", "app.pem"));
  chmodSync(join("secrets", "app.pem"), 0o600);

  // Write .env atomically (build in memory then write once)
  const envContent = buildEnvContent(config);
  writeFileSync(".env", envContent, { encoding: "utf8" });
  chmodSync(".env", 0o600);

  console.log("  .env written (mode 600)");
  console.log("  secrets/app.pem copied (mode 600)");
}

async function dockerBuildAndLaunch(
  rl: ReturnType<typeof createInterface>
): Promise<void> {
  console.log("\n── Step 8: Docker ─────────────────────────────────────────");
  const wantLaunch = await promptYesNo(
    rl,
    "Build and launch Last Light with Docker now?",
    true
  );

  if (!wantLaunch) {
    console.log("\nWhen ready, run:");
    console.log("  docker compose --profile build-only build sandbox");
    console.log("  docker compose up -d");
    return;
  }

  console.log("\nBuilding sandbox image...");
  try {
    execSync("docker compose --profile build-only build sandbox", {
      stdio: "inherit",
    });
  } catch {
    console.error(
      "Build failed. Check the output above and ensure Docker Compose v2 is installed."
    );
    process.exit(1);
  }

  console.log("\nStarting services...");
  try {
    execSync("docker compose up -d", { stdio: "inherit" });
  } catch {
    console.error("docker compose up failed. Check the output above.");
    process.exit(1);
  }

  // Check status
  try {
    execSync("docker compose ps", { stdio: "inherit" });
  } catch {
    // Non-fatal — status check is informational
  }
}

function printSummary(domain: string, webhookSecret: string): void {
  console.log("\n── Step 9: Done! ──────────────────────────────────────────");
  console.log(`\nWebhook URL:   https://${domain}/webhook`);
  console.log(`Dashboard URL: https://${domain}/admin`);
  console.log(`\nREMINDER: Paste this WEBHOOK_SECRET into your GitHub App settings:`);
  console.log(`  ${webhookSecret}`);
  console.log(`\nNext steps:`);
  console.log(`  - Read agent-context/rules.md to customise bot behaviour`);
  console.log(`  - Verify webhook delivery in GitHub App settings`);
  console.log(`  - Check logs: docker compose logs -f\n`);
}

// ── Main entry point ─────────────────────────────────────────────────────────

export async function runSetup(): Promise<void> {
  if (!process.stdin.isTTY) {
    console.error("Error: setup must be run interactively (stdin must be a TTY).");
    process.exit(1);
  }

  console.log("\nLast Light Setup Wizard");
  console.log("=======================");
  console.log("This wizard will configure Last Light on your server.\n");

  // Step 0 — Pre-flight
  preflight();

  const rl = createInterface({ input: process.stdin, output: process.stdout });

  try {
    // Step 1 — GitHub App
    const { appId, installationId, pemSourcePath } = await collectGitHubApp(rl);

    // Step 2 — Secrets
    const { webhookSecret, adminSecret } = generateSecrets();

    // Step 3 — Domain + TLS
    const { domain, useCaddy } = await collectDomain(rl);

    // Step 4 — Anthropic key
    const anthropicKey = await collectAnthropicKey(rl);

    // Step 5 — Admin password
    const adminPassword = await collectAdminPassword(rl);

    // Step 6 — Slack
    const { botToken, appToken, deliveryChannel, allowedUsers } =
      await collectSlack(rl);

    // Step 7 — Write config
    const config: SetupConfig = {
      GITHUB_APP_ID: appId,
      GITHUB_APP_INSTALLATION_ID: installationId,
      WEBHOOK_SECRET: webhookSecret,
      ADMIN_SECRET: adminSecret,
      DOMAIN: domain,
      ANTHROPIC_API_KEY: anthropicKey,
      ADMIN_PASSWORD: adminPassword,
      SLACK_BOT_TOKEN: botToken,
      SLACK_APP_TOKEN: appToken,
      SLACK_DELIVERY_CHANNEL: deliveryChannel,
      SLACK_ALLOWED_USERS: allowedUsers,
      useCaddy,
      pemSourcePath,
    };
    writeConfig(config);

    // Step 8 — Docker
    await dockerBuildAndLaunch(rl);

    // Step 9 — Summary
    printSummary(domain, webhookSecret);
  } finally {
    rl.close();
  }
}
