#!/usr/bin/env node
/**
 * Last Light setup wizard — `npx lastlight setup`
 *
 * Guides a user from a bare server to a fully configured Last Light instance.
 * Uses @clack/prompts for the interactive UI and chalk for styling.
 */

import { randomBytes } from "node:crypto";
import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  chmodSync,
  copyFileSync,
} from "node:fs";
import { resolve, join } from "node:path";
import { execSync } from "node:child_process";
import * as p from "@clack/prompts";
import chalk from "chalk";

// ── Brand colors ───────────────────────────────────────────────────────────

const gold = chalk.hex("#F0B429");
const teal = chalk.hex("#1A7A8A");
const orange = chalk.hex("#E8752A");
const dim = chalk.dim;
const bright = chalk.white.bold;

// ── Types ───────────────────────────────────────────────────────────────────

export interface SetupConfig {
  GITHUB_APP_ID: string;
  GITHUB_APP_INSTALLATION_ID: string;
  WEBHOOK_SECRET: string;
  ADMIN_SECRET: string;
  DOMAIN: string;
  ANTHROPIC_API_KEY: string;
  ADMIN_PASSWORD?: string;
  SLACK_BOT_TOKEN?: string;
  SLACK_APP_TOKEN?: string;
  SLACK_DELIVERY_CHANNEL?: string;
  SLACK_ALLOWED_USERS?: string;
  useCaddy: boolean;
  pemSourcePath: string;
}

// ── Validation helpers (exported for unit tests) ────────────────────────────

export function isPositiveInt(s: string): boolean {
  return /^\d+$/.test(s) && parseInt(s, 10) > 0;
}

export function isPemFile(filePath: string): boolean {
  try {
    const content = readFileSync(filePath, "utf8");
    return (
      content.startsWith("-----BEGIN RSA PRIVATE KEY-----") ||
      content.startsWith("-----BEGIN PRIVATE KEY-----")
    );
  } catch {
    return false;
  }
}

export function isAnthropicKey(s: string): boolean {
  return s.startsWith("sk-ant-");
}

export function isSlackBotToken(s: string): boolean {
  return s.startsWith("xoxb-");
}

export function isSlackAppToken(s: string): boolean {
  return s.startsWith("xapp-");
}

// ── .env serialization (exported for unit tests) ────────────────────────────

export function buildEnvContent(config: SetupConfig): string {
  const lines: string[] = [
    "# ── Last Light — Environment Variables ─────────────────────",
    "# Generated by: npx lastlight setup",
    "",
    "# ── GitHub App (required) ────────────────────────────────",
    `GITHUB_APP_ID=${config.GITHUB_APP_ID}`,
    `GITHUB_APP_PRIVATE_KEY_PATH=./secrets/app.pem`,
    `GITHUB_APP_INSTALLATION_ID=${config.GITHUB_APP_INSTALLATION_ID}`,
    "",
    "# ── Webhook (required) ──────────────────────────────────",
    `WEBHOOK_SECRET=${config.WEBHOOK_SECRET}`,
    "",
    "# ── Domain (used by Caddy for TLS) ─────────────────────────────────────",
    `DOMAIN=${config.DOMAIN}`,
    "",
    "# ── Claude API ───────────────────────────────────────────",
    `ANTHROPIC_API_KEY=${config.ANTHROPIC_API_KEY}`,
    "",
    "# ── Admin Dashboard ────────────────────────────────────────",
    `ADMIN_SECRET=${config.ADMIN_SECRET}`,
  ];

  if (config.ADMIN_PASSWORD) {
    lines.push(`ADMIN_PASSWORD=${config.ADMIN_PASSWORD}`);
  }

  if (config.SLACK_BOT_TOKEN) {
    lines.push("");
    lines.push("# ── Slack ──────────────────────────────────────────────────");
    lines.push(`SLACK_BOT_TOKEN=${config.SLACK_BOT_TOKEN}`);
    if (config.SLACK_APP_TOKEN) {
      lines.push(`SLACK_APP_TOKEN=${config.SLACK_APP_TOKEN}`);
    }
    if (config.SLACK_DELIVERY_CHANNEL) {
      lines.push(`SLACK_DELIVERY_CHANNEL=${config.SLACK_DELIVERY_CHANNEL}`);
    }
    if (config.SLACK_ALLOWED_USERS) {
      lines.push(`SLACK_ALLOWED_USERS=${config.SLACK_ALLOWED_USERS}`);
    }
  }

  lines.push("");
  return lines.join("\n");
}

// ── Clack helper — bail on cancel ───────────────────────────────────────────

function required<T>(value: T | symbol): T {
  if (p.isCancel(value)) {
    p.cancel("Setup cancelled.");
    process.exit(0);
  }
  return value;
}

// ── Banner ──────────────────────────────────────────────────────────────────

function printBanner(): void {
  console.log();
  console.log(gold("  ╭──────────────────────────────────────────────╮"));
  console.log(gold("  │") + "                                              " + gold("│"));
  console.log(gold("  │") + bright("        ✦  L A S T   L I G H T  ✦           ") + gold("│"));
  console.log(gold("  │") + "                                              " + gold("│"));
  console.log(gold("  │") + dim("     GitHub Repository Maintenance Agent     ") + gold("│"));
  console.log(gold("  │") + "                                              " + gold("│"));
  console.log(gold("  ╰──────────────────────────────────────────────╯"));
  console.log();
}

// ── Preflight ───────────────────────────────────────────────────────────────

function preflight(): void {
  if (!existsSync("docker-compose.yml")) {
    if (existsSync("lastlight/docker-compose.yml")) {
      p.log.info("Found existing lastlight/ directory — continuing setup there.");
      process.chdir("lastlight");
    } else {
      const s = p.spinner();
      s.start("Cloning cliftonc/lastlight ...");
      try {
        execSync("git clone https://github.com/cliftonc/lastlight.git lastlight", {
          stdio: "pipe",
        });
        s.stop("Repository cloned.");
      } catch {
        s.stop("Clone failed.");
        p.log.error("Failed to clone. Please clone manually:");
        p.log.info("  git clone https://github.com/cliftonc/lastlight.git");
        process.exit(1);
      }
      process.chdir("lastlight");
      p.log.info(`Working directory: ${dim(process.cwd())}`);
    }
  }

  try {
    execSync("docker info", { stdio: "ignore" });
  } catch {
    p.log.error("Docker is not running or not installed.");
    p.log.info("Please start Docker and re-run: " + teal("npx lastlight setup"));
    process.exit(1);
  }

  if (existsSync(".env")) {
    p.log.error(".env already exists. To reconfigure, remove it first: " + dim("rm .env"));
    process.exit(1);
  }
}

// ── Setup steps ─────────────────────────────────────────────────────────────

async function collectGitHubApp(): Promise<{
  appId: string;
  installationId: string;
  pemSourcePath: string;
}> {
  p.log.step(gold("GitHub App"));
  p.log.info(
    dim("Create one at ") +
    teal("https://github.com/settings/apps/new") +
    dim(" if you haven't already.")
  );

  const appId = required(
    await p.text({
      message: "GitHub App ID",
      placeholder: "123456",
      validate: (v) =>
        v && isPositiveInt(v) ? undefined : "Must be a positive integer.",
    }),
  );

  const installationId = required(
    await p.text({
      message: "Installation ID",
      placeholder: "789012",
      validate: (v) =>
        v && isPositiveInt(v) ? undefined : "Must be a positive integer.",
    }),
  );

  const pemPath = required(
    await p.text({
      message: "Path to private key (.pem)",
      placeholder: "~/downloads/your-app.private-key.pem",
      validate: (v) =>
        v && isPemFile(resolve(v)) ? undefined : "File not found or not a valid PEM.",
    }),
  );

  return {
    appId: appId as string,
    installationId: installationId as string,
    pemSourcePath: resolve(pemPath as string),
  };
}

async function collectDomain(): Promise<{ domain: string; useCaddy: boolean }> {
  p.log.step(gold("Domain & TLS"));

  const domain = required(
    await p.text({
      message: "Your domain",
      placeholder: "lastlight.example.com",
      validate: (v) =>
        v && v.length > 0 && v.includes(".")
          ? undefined
          : "Enter a valid domain name.",
    }),
  );

  const useCaddy = required(
    await p.confirm({
      message: "Use Caddy for automatic TLS?",
      initialValue: true,
    }),
  );

  p.log.info(`Webhook URL: ${teal(`https://${domain}/webhook`)}`);

  return { domain: domain as string, useCaddy: useCaddy as boolean };
}

async function collectAnthropicKey(): Promise<string> {
  p.log.step(gold("Anthropic API Key"));

  const key = required(
    await p.text({
      message: "ANTHROPIC_API_KEY",
      placeholder: "sk-ant-...",
      validate: (v) =>
        v && isAnthropicKey(v) ? undefined : "Must start with sk-ant-",
    }),
  );

  return key as string;
}

async function collectAdminPassword(): Promise<string | undefined> {
  p.log.step(gold("Admin Dashboard"));

  const wantPassword = required(
    await p.confirm({
      message: "Set an admin dashboard password?",
      initialValue: false,
    }),
  );
  if (!wantPassword) return undefined;

  const password = required(
    await p.password({
      message: "Admin password",
      validate: (v) =>
        v && v.length >= 8 ? undefined : "Must be at least 8 characters.",
    }),
  );

  return password as string;
}

async function collectSlack(): Promise<{
  botToken?: string;
  appToken?: string;
  deliveryChannel?: string;
  allowedUsers?: string;
}> {
  p.log.step(gold("Slack") + dim(" (optional)"));

  const wantSlack = required(
    await p.confirm({
      message: "Enable Slack integration?",
      initialValue: false,
    }),
  );
  if (!wantSlack) return {};

  const botToken = required(
    await p.text({
      message: "SLACK_BOT_TOKEN",
      placeholder: "xoxb-...",
      validate: (v) =>
        v && isSlackBotToken(v) ? undefined : "Must start with xoxb-",
    }),
  ) as string;

  const appToken = required(
    await p.text({
      message: "SLACK_APP_TOKEN",
      placeholder: "xapp-...",
      validate: (v) =>
        v && isSlackAppToken(v) ? undefined : "Must start with xapp-",
    }),
  ) as string;

  const deliveryChannel = required(
    await p.text({
      message: "Delivery channel ID",
      placeholder: "C0123456789 (press Enter to skip)",
      defaultValue: "",
    }),
  ) as string;

  const allowedUsers = required(
    await p.text({
      message: "Allowed user IDs",
      placeholder: "U0123,U0456 (press Enter to skip)",
      defaultValue: "",
    }),
  ) as string;

  return {
    botToken,
    appToken,
    deliveryChannel: deliveryChannel || undefined,
    allowedUsers: allowedUsers || undefined,
  };
}

function writeConfig(config: SetupConfig): void {
  p.log.step(gold("Writing config"));

  try {
    mkdirSync("secrets", { recursive: true });
  } catch (err: unknown) {
    const e = err as NodeJS.ErrnoException;
    if (e.code === "EACCES") {
      p.log.error("Permission denied creating secrets/ directory.");
      process.exit(1);
    }
    throw err;
  }

  copyFileSync(config.pemSourcePath, join("secrets", "app.pem"));
  chmodSync(join("secrets", "app.pem"), 0o600);

  const envContent = buildEnvContent(config);
  writeFileSync(".env", envContent, { encoding: "utf8" });
  chmodSync(".env", 0o600);

  p.log.success(
    dim("secrets/app.pem") + " copied " + dim("(mode 600)") + "\n" +
    "  " + dim(".env") + " written " + dim("(mode 600)")
  );
}

async function dockerBuildAndLaunch(): Promise<void> {
  p.log.step(gold("Docker"));

  const wantLaunch = required(
    await p.confirm({
      message: "Build and launch Last Light now?",
      initialValue: true,
    }),
  );

  if (!wantLaunch) {
    p.log.info("When ready, run:\n" +
      dim("  docker compose --profile build-only build sandbox\n") +
      dim("  docker compose up -d"));
    return;
  }

  const s = p.spinner();

  s.start("Building sandbox image...");
  try {
    execSync("docker compose --profile build-only build sandbox", {
      stdio: "pipe",
    });
    s.stop("Sandbox image built.");
  } catch {
    s.stop("Sandbox build failed.");
    p.log.error("Check Docker Compose v2 is installed.");
    process.exit(1);
  }

  s.start("Starting services...");
  try {
    execSync("docker compose up -d", { stdio: "pipe" });
    s.stop("Services started.");
  } catch {
    s.stop("Failed to start services.");
    p.log.error("Check docker compose logs for details.");
    process.exit(1);
  }
}

function printSummary(domain: string, webhookSecret: string): void {
  console.log();
  console.log(gold("  ┌──────────────────────────────────────────────┐"));
  console.log(gold("  │") + bright("  Setup complete!                              ") + gold("│"));
  console.log(gold("  └──────────────────────────────────────────────┘"));
  console.log();
  console.log("  " + dim("Webhook URL   ") + teal(`https://${domain}/webhook`));
  console.log("  " + dim("Dashboard     ") + teal(`https://${domain}/admin`));
  console.log();
  console.log("  " + orange("Paste this WEBHOOK_SECRET into your GitHub App settings:"));
  console.log("  " + bright(webhookSecret));
  console.log();
  console.log("  " + dim("Next steps:"));
  console.log("  " + dim("  • Edit agent-context/rules.md to customise bot behaviour"));
  console.log("  " + dim("  • Verify webhook delivery in GitHub App settings"));
  console.log("  " + dim("  • Check logs: ") + teal("docker compose logs -f"));
  console.log();
}

// ── Main entry point ─────────────────────────────────────────────────────────

export async function runSetup(): Promise<void> {
  if (!process.stdin.isTTY) {
    console.error("Error: setup must be run interactively (stdin must be a TTY).");
    process.exit(1);
  }

  printBanner();

  p.intro(dim("This wizard will configure Last Light on your server."));

  preflight();

  const { appId, installationId, pemSourcePath } = await collectGitHubApp();
  const webhookSecret = randomBytes(32).toString("hex");
  const adminSecret = randomBytes(32).toString("hex");
  p.log.success("Secrets auto-generated " + dim("(WEBHOOK_SECRET + ADMIN_SECRET)"));

  const { domain, useCaddy } = await collectDomain();
  const anthropicKey = await collectAnthropicKey();
  const adminPassword = await collectAdminPassword();
  const { botToken, appToken, deliveryChannel, allowedUsers } = await collectSlack();

  const config: SetupConfig = {
    GITHUB_APP_ID: appId,
    GITHUB_APP_INSTALLATION_ID: installationId,
    WEBHOOK_SECRET: webhookSecret,
    ADMIN_SECRET: adminSecret,
    DOMAIN: domain,
    ANTHROPIC_API_KEY: anthropicKey,
    ADMIN_PASSWORD: adminPassword,
    SLACK_BOT_TOKEN: botToken,
    SLACK_APP_TOKEN: appToken,
    SLACK_DELIVERY_CHANNEL: deliveryChannel,
    SLACK_ALLOWED_USERS: allowedUsers,
    useCaddy,
    pemSourcePath,
  };

  writeConfig(config);
  await dockerBuildAndLaunch();

  p.outro(gold("Last Light is ready."));
  printSummary(domain, webhookSecret);
}
